name: Main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout changes"
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
      - name: "Install"
        run: "yarn install"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: "${{ secrets.NPMJS_ACCESS_TOKEN }}"
          access: "public"
